export const SIGN_UP_BUILDER = "Sign Up Builder";
export const VIEW_FULL_SCREEN = "View Full Screen";
export const BUILDER='Builder';
export const TEMPLATES='Templates';
export const REDO_BUTTON='redo button';
export const UNDO_BUTTON='undo button'

export const signup_builder_sidebar = {
  LOGIN_TYPES: "Login Types",
  STYLING: "Styling",
  BRAND_ASSESSTS: "Brand Assessts",
  SOCIAL_LOGINS: "Social Logins",
  LOGINS_LIMIT: "You can select only 4 social logins.",
  WORK_EMAIL_PASS_LESS_LOGIN: "Work Email & Password-less Logins",
  USER_APPROVELS: "User Approvals",
  THEME: "Theme",
  LAYOUT: "Layout",
  BUTTONS: "Buttons",
  COLORS: "Colors",
  INPUT_FIELD: "Input Field",
  TYPOGRAPHY: "Typography",
  GRID: "Grid",
  SLIDER_WIDTH_INSTRUCTION:
    "Adjust the width with the slider to customize the spacing to the respective sections",
  BACKGROUND: "Background",
  SOCIAL_BUTTON_STYLING: "Social Button Styling",
  POSITION: "Position",
  SOCIAL_BUTTON_STATE: "Social Button State",
  FONT_SIZE: "Font Size",
  FONT_WEIGHT: "Font Weight",
  FONT_COLOR: "Font Color",
  BACKGROUND_COLOR: "Background Color",
  BORDER_RADIUS: "Border Radius",
  SUBMIT_BUTTON_STYLING: "Submit Button Styling",
  PRIMARY_COLOR: "Primary Color",
  ERROR_COLOR: "Error Color",
  FIELD_STATE: "Field State",
  BOX_BORDER: "Box Border",
  LABEL_FONT_STATE: "Label Font State",
  LABEL_FONT_WEIGHT: "Label Font Weight",
  LABEL_COLOR: "Label Color",
  REF_TEXT_SIZES: "Reference text Sizes",
  FONT_URL: "Font URL",
  FONT_URL_INSTRUCTION: "This URL must be a woff or woff2 font file type",
  SELECT_FONT: "Select Font",
  OR: "OR",
  TITLE: "Title",
  SUB_TITLE: "Sub-Title",
  LINKS: "Links",
  LINKS_STYLE: "Links Style",
  COMPANY_LOGO: "Company Logo",
  UPLOAD_LOGO: "Upload Logo",
  CLICK_AND_DRAG_FILE: "Click or drag file to this area to upload",
  UPLOAD_IMAGE_SUPPORT_SIZE_INSTRUCTION:
    "Support JPEG, PNG, SVG, ICO Max file size: 1.0 MB",
  ALIGNMANT: "Alignment",
  SIGN_UP_BOX_TITLE: "SignUp Box Title",
  CUSTOM_LAYOUT_FOR_CONTENT: "Custom Layouts for Content",
  LAYOUT_SELECT_INSTRUCTOIN: "You can select up-to 2 layouts.",
  SIGN_UP_TITLE:'Sign Up Title',
  CONTENT:'Content',
  TESTIMONAL:'Testimonal',
  EDIT_STATEMENT:'Edit Statement',
  STATEMENT_TITLE:'Statement Title',
  STATEMENT_SUB_TITLE:'statement Sub-Title',
  IMAGE_SHAPE:'Image Shape',
  ADD_TESTIMONAL:'Add Testimonal',
  EDIT_TESTIMONAL:'Edit Testimonial',
  CLOSE:'Close',
  IMAGE:'ImageName',
  NAME:'Name',
  DESIGNATION:'Designation',
  QUOTE:'Quote',
  MINUS_BUTTON:'Minus Button',
  PLUS_BUTTON:'Plus Button',
  ADD_INPUT_FIELD:'Add Input Field',
TOP_ALIGN:'top align',
BOTTOM_ALIGN:'bottom align',
EDIT_BUTTON:'Edit Button',
BACK_BUTTON:'Back Button',
ADD_LOGO:'Add Logo'
};

export const AriaLabel = {
  MOBILE_VIEW: "mobile view button",
  TABLET_VIEW: "tablet view button",
  DESKTOP_VIEW_BUTTON: "desktop view button",
  FULL_SCREEN_VIEW: "fullscreen view",
};
